#!/usr/bin/env bash
# scripts/build-uda-inventory.sh — aggregate UDAs from all profile .taskrc files
set -euo pipefail

WW_BASE="${WW_BASE:-$HOME/ww}"
OUT_DIR="$WW_BASE/resources/inventory"
OUT_FILE="$OUT_DIR/uda-registry.yaml"

usage() {
  cat <<'EOF'
Usage: build-uda-inventory.sh [--print]

Scans all profile .taskrc files for uda.* entries and writes
resources/inventory/uda-registry.yaml.
--print   Print YAML to stdout instead of writing to file.
EOF
}

[[ "${1:-}" == "--help" || "${1:-}" == "-h" ]] && { usage; exit 0; }
PRINT_ONLY="${1:-}"

declare -A uda_label uda_type uda_values uda_description
declare -A uda_origins  # name → comma-separated list of profile names

profile_count=0

for pdir in "$WW_BASE/profiles"/*/; do
  [[ -d "$pdir" ]] || continue
  pname=$(basename "$pdir")
  taskrc="$pdir/.taskrc"
  [[ -f "$taskrc" ]] || continue
  ((profile_count++)) || true

  while IFS='=' read -r key val; do
    key="${key## }"; key="${key%% }"
    val="${val## }"; val="${val%% }"
    [[ "$key" == uda.*.* ]] || continue
    # key format: uda.<name>.<field>
    rest="${key#uda.}"
    uname="${rest%%.*}"
    field="${rest#*.}"
    case "$field" in
      label)       uda_label["$uname"]="$val" ;;
      type)        uda_type["$uname"]="$val" ;;
      values)      uda_values["$uname"]="$val" ;;
      description) uda_description["$uname"]="$val" ;;
    esac
    # Track which profiles define this UDA
    if [[ -n "${uda_origins[$uname]:-}" ]]; then
      if [[ "${uda_origins[$uname]}" != *"$pname"* ]]; then
        uda_origins["$uname"]="${uda_origins[$uname]}, $pname"
      fi
    else
      uda_origins["$uname"]="$pname"
    fi
  done < <(grep -E '^uda\.' "$taskrc" 2>/dev/null || true)
done

mapfile -t uda_names < <(printf '%s\n' "${!uda_origins[@]}" | sort)

yaml="# uda-registry.yaml — generated by build-uda-inventory.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Profiles scanned: ${profile_count}  UDAs found: ${#uda_names[@]}
udas:"
for n in "${uda_names[@]}"; do
  yaml+=$'\n'"  - name: \"${n}\""
  [[ -n "${uda_label[$n]:-}"       ]] && yaml+=$'\n'"    label: \"${uda_label[$n]}\""
  [[ -n "${uda_type[$n]:-}"        ]] && yaml+=$'\n'"    type: \"${uda_type[$n]}\""
  [[ -n "${uda_values[$n]:-}"      ]] && yaml+=$'\n'"    values: \"${uda_values[$n]}\""
  [[ -n "${uda_description[$n]:-}" ]] && yaml+=$'\n'"    description: \"${uda_description[$n]}\""
  yaml+=$'\n'"    profile_origins: [${uda_origins[$n]}]"
done

if [[ "$PRINT_ONLY" == "--print" ]]; then
  echo "$yaml"
else
  mkdir -p "$OUT_DIR"
  echo "$yaml" > "$OUT_FILE"
  printf "Wrote %s (%d UDAs from %d profiles)\n" "$OUT_FILE" "${#uda_names[@]}" "$profile_count"
fi
