#!/usr/bin/env bash
# scripts/build-ledger-inventory.sh — aggregate hledger accounts + commodities across all profiles
set -euo pipefail

WW_BASE="${WW_BASE:-$HOME/ww}"
OUT_DIR="$WW_BASE/resources/inventory"
OUT_FILE="$OUT_DIR/ledger-accounts.yaml"

usage() {
  cat <<'EOF'
Usage: build-ledger-inventory.sh [--print]

Scans all profile ledger files and writes resources/inventory/ledger-accounts.yaml.
--print   Print YAML to stdout instead of writing to file.
EOF
}

[[ "${1:-}" == "--help" || "${1:-}" == "-h" ]] && { usage; exit 0; }
PRINT_ONLY="${1:-}"

declare -A seen_accounts seen_commodities
profile_count=0
ledger_count=0

for pdir in "$WW_BASE/profiles"/*/; do
  [[ -d "$pdir" ]] || continue
  pname=$(basename "$pdir")
  # Scan known ledger file locations
  ledger_candidates=(
    "$pdir/ledger/${pname}.journal"
    "$pdir/ledgers/${pname}.journal"
    "$pdir/${pname}.journal"
  )
  # Also scan jrnl.yaml-declared ledger paths (simple grep for .journal lines)
  jrnl_yaml="$pdir/.config/jrnl.yaml"
  if [[ -f "$jrnl_yaml" ]]; then
    while IFS= read -r line; do
      f=$(echo "$line" | awk '{print $NF}')
      [[ -f "$f" ]] && ledger_candidates+=("$f")
    done < <(grep '\.journal' "$jrnl_yaml" 2>/dev/null || true)
  fi
  found_any=0
  for lf in "${ledger_candidates[@]}"; do
    [[ -f "$lf" ]] || continue
    found_any=1
    ((ledger_count++)) || true
    # Extract accounts via hledger if available
    if command -v hledger &>/dev/null; then
      while IFS= read -r acc; do
        [[ -n "$acc" ]] && seen_accounts["$acc"]=1
      done < <(hledger -f "$lf" accounts 2>/dev/null || true)
      while IFS= read -r com; do
        [[ -n "$com" ]] && seen_commodities["$com"]=1
      done < <(hledger -f "$lf" commodities 2>/dev/null || true)
    else
      # Fallback: grep posting lines (lines starting with whitespace + account)
      while IFS= read -r line; do
        acc=$(echo "$line" | awk '{print $1}')
        [[ -n "$acc" ]] && seen_accounts["$acc"]=1
      done < <(grep -E '^\s+[A-Za-z]' "$lf" 2>/dev/null | awk '{print $1}' | sort -u || true)
    fi
  done
  [[ $found_any -eq 1 ]] && ((profile_count++)) || true
done

# Build sorted arrays
mapfile -t accounts < <(printf '%s\n' "${!seen_accounts[@]}" | sort)
mapfile -t commodities < <(printf '%s\n' "${!seen_commodities[@]}" | sort)

yaml="# ledger-accounts.yaml — generated by build-ledger-inventory.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Profiles scanned: ${profile_count}  Ledger files: ${ledger_count}
accounts:"
for a in "${accounts[@]}"; do yaml+=$'\n'"  - \"${a}\""; done
yaml+=$'\ncommodities:'
for c in "${commodities[@]}"; do yaml+=$'\n'"  - \"${c}\""; done

if [[ "$PRINT_ONLY" == "--print" ]]; then
  echo "$yaml"
else
  mkdir -p "$OUT_DIR"
  echo "$yaml" > "$OUT_FILE"
  echo "Wrote $OUT_FILE (${#accounts[@]} accounts, ${#commodities[@]} commodities)"
fi
